const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.Facebook,
		C3.Plugins.advert,
		C3.Plugins.Mouse,
		C3.Plugins.Text,
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.Physics,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.Timer,
		C3.Behaviors.scrollto,
		C3.Behaviors.solid,
		C3.Behaviors.Sin,
		C3.Behaviors.Rotate,
		C3.Plugins.Particles,
		C3.Plugins.progressbar,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Exps.min,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Behaviors.Physics.Acts.ApplyImpulseAtAngle,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.Physics.Exps.VelocityX,
		C3.Behaviors.Physics.Exps.VelocityY,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Behaviors.Physics.Acts.SetVelocity,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Acts.RotateClockwise,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Particles.Acts.SetPos,
		C3.Plugins.Touch.Cnds.OnDoubleTapGestureObject,
		C3.Plugins.Facebook.Acts.LogIn2,
		C3.Plugins.Facebook.Cnds.OnLogIn,
		C3.Plugins.Facebook.Cnds.OnNameAvailable,
		C3.Plugins.Sprite.Exps.IID,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.advert.Acts.CreateRewarded,
		C3.Plugins.advert.Acts.ShowRewarded,
		C3.Plugins.advert.Cnds.OnRewardedComplete,
		C3.Behaviors.Physics.Acts.SetImmovable,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.progressbar.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.loadingprogress
	];
};
self.C3_JsPropNameTable = [
	{Touch: 0},
	{Audio: 0},
	{Facebook: 0},
	{MobileAdvert: 0},
	{Mouse: 0},
	{Text_YouWin: 0},
	{Text_YouLose: 0},
	{SplashScreenBackground: 0},
	{play_btn: 0},
	{credit_btn: 0},
	{Music_off_btn: 0},
	{Music_on_btn: 0},
	{facebook_btn: 0},
	{credit_icon_text: 0},
	{Credit_background: 0},
	{credit_text: 0},
	{back_btn: 0},
	{btn_1: 0},
	{btn_10: 0},
	{btn_11: 0},
	{btn_12: 0},
	{btn_13: 0},
	{btn_14: 0},
	{btn_15: 0},
	{btn_16: 0},
	{btn_2: 0},
	{btn_3: 0},
	{btn_4: 0},
	{btn_5: 0},
	{btn_6: 0},
	{btn_7: 0},
	{btn_8: 0},
	{btn_9: 0},
	{Digit_10: 0},
	{Digit_1: 0},
	{Digit_11: 0},
	{Digit_12: 0},
	{Digit_13: 0},
	{Digit_14: 0},
	{Digit_15: 0},
	{Digit_16: 0},
	{Digit_2: 0},
	{Digit_3: 0},
	{Digit_4: 0},
	{Digit_5: 0},
	{Digit_6: 0},
	{Digit_7: 0},
	{Digit_8: 0},
	{Digit_9: 0},
	{Rating1: 0},
	{Rating2: 0},
	{Rating3: 0},
	{Rating4: 0},
	{Rating5: 0},
	{Rating6: 0},
	{Rating7: 0},
	{Rating8: 0},
	{Rating9: 0},
	{Rating10: 0},
	{Rating11: 0},
	{Rating12: 0},
	{Rating13: 0},
	{Rating14: 0},
	{Rating15: 0},
	{Rating16: 0},
	{level_selection_background: 0},
	{back_btn2: 0},
	{level_box: 0},
	{level_text: 0},
	{isCreated: 0},
	{isFalling: 0},
	{canFail: 0},
	{Physics: 0},
	{DragDrop: 0},
	{soil: 0},
	{RotatingIcon: 0},
	{ground2: 0},
	{IsHit: 0},
	{FlowerPot2: 0},
	{collectible: 0},
	{level1_background: 0},
	{Drag_Drop_Text: 0},
	{Heart: 0},
	{HeartCount: 0},
	{soil2: 0},
	{soil3: 0},
	{Lose_text: 0},
	{pauseFrame: 0},
	{Pause_Text: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Text_Resume: 0},
	{Text_Restart: 0},
	{Text_Exit: 0},
	{pause_btn: 0},
	{LevelComplete: 0},
	{WinFrame: 0},
	{home_btn: 0},
	{Next_btn: 0},
	{Rating: 0},
	{Retry_btn: 0},
	{Ground: 0},
	{hasLaunched: 0},
	{Timer: 0},
	{ScrollTo: 0},
	{Ball: 0},
	{Anchor: 0},
	{Solid: 0},
	{Target: 0},
	{TargetZone: 0},
	{RopeLine: 0},
	{Dot: 0},
	{DropWater: 0},
	{Sprite: 0},
	{Sine: 0},
	{RedBallHorizontal: 0},
	{RedBallVertical: 0},
	{Sine2: 0},
	{RedBallCircular: 0},
	{Plank: 0},
	{btnMovePlank: 0},
	{Box: 0},
	{btnMoveBox: 0},
	{Channel: 0},
	{Receiver: 0},
	{Sender: 0},
	{Rotate: 0},
	{Teleporter: 0},
	{FlowerPot: 0},
	{Background: 0},
	{Background2: 0},
	{Background3: 0},
	{Backgroun4: 0},
	{Platform: 0},
	{DropZone: 0},
	{Text: 0},
	{pot_trigger: 0},
	{btnMoveBox2: 0},
	{btnMoveBox3: 0},
	{Box2: 0},
	{Box3: 0},
	{Retrylogo: 0},
	{Plank2: 0},
	{btnMovePlank2: 0},
	{seed: 0},
	{Plank3: 0},
	{btnMovePlank3: 0},
	{RedBallIdeal: 0},
	{CollisionPlank: 0},
	{Water: 0},
	{Box4: 0},
	{btnMoveBox4: 0},
	{Plank4: 0},
	{btnMovePlank4: 0},
	{Plank5: 0},
	{btnMovePlank5: 0},
	{BallTrailideal: 0},
	{BallTrailHorizontal: 0},
	{BallTrailVertical: 0},
	{BallTrailcircular: 0},
	{Rotating: 0},
	{Level6_Background: 0},
	{Box5: 0},
	{btnMoveBox5: 0},
	{level12_backgound: 0},
	{Box6: 0},
	{btnMoveBox6: 0},
	{Plank6: 0},
	{btnMovePlank6: 0},
	{splash_background: 0},
	{SplashBackground: 0},
	{Value: 0},
	{ProgressBar: 0},
	{Sprite2: 0},
	{Family1: 0},
	{CurrentLevel: 0},
	{LevelRating1: 0},
	{LevelRating2: 0},
	{LevelRating3: 0},
	{LevelRating4: 0},
	{LevelRating5: 0},
	{LevelRating6: 0},
	{LevelRating7: 0},
	{LevelRating8: 0},
	{LevelRating9: 0},
	{LevelRating10: 0},
	{LevelRating11: 0},
	{LevelRating12: 0},
	{LevelRating13: 0},
	{LevelRating14: 0},
	{LevelRating15: 0},
	{LevelRating16: 0},
	{IsDragging: 0},
	{hasScored: 0},
	{MAX_PULL: 0},
	{angleToTouch: 0},
	{distanceToTouch: 0},
	{numDots: 0},
	{dotSpacing: 0},
	{gravity: 0},
	{dotIndex: 0},
	{IgnoreLoseCheck: 0},
	{SoundMuted: 0},
	{TeleporterFrom: 0},
	{Jumping: 0},
	{RatingCount1: 0},
	{GamePaused: 0},
	{Soil_VelX: 0},
	{Soil_VelY: 0},
	{RatingCount2: 0},
	{RatingCount3: 0},
	{RatingCount4: 0},
	{RatingCount5: 0},
	{RatingCount6: 0},
	{RatingCount7: 0},
	{RatingCount8: 0},
	{RatingCount9: 0},
	{RatingCount10: 0},
	{RatingCount11: 0},
	{RatingCount12: 0},
	{RatingCount13: 0},
	{RatingCount14: 0},
	{RatingCount15: 0},
	{RatingCount16: 0}
];

self.InstanceType = {
	Touch: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Facebook: class extends self.IInstance {},
	MobileAdvert: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Text_YouWin: class extends self.ITextInstance {},
	Text_YouLose: class extends self.ITextInstance {},
	SplashScreenBackground: class extends self.ITiledBackgroundInstance {},
	play_btn: class extends self.ISpriteInstance {},
	credit_btn: class extends self.ISpriteInstance {},
	Music_off_btn: class extends self.ISpriteInstance {},
	Music_on_btn: class extends self.ISpriteInstance {},
	facebook_btn: class extends self.ISpriteInstance {},
	credit_icon_text: class extends self.ITextInstance {},
	Credit_background: class extends self.ISpriteInstance {},
	credit_text: class extends self.ITextInstance {},
	back_btn: class extends self.ISpriteInstance {},
	btn_1: class extends self.ISpriteInstance {},
	btn_10: class extends self.ISpriteInstance {},
	btn_11: class extends self.ISpriteInstance {},
	btn_12: class extends self.ISpriteInstance {},
	btn_13: class extends self.ISpriteInstance {},
	btn_14: class extends self.ISpriteInstance {},
	btn_15: class extends self.ISpriteInstance {},
	btn_16: class extends self.ISpriteInstance {},
	btn_2: class extends self.ISpriteInstance {},
	btn_3: class extends self.ISpriteInstance {},
	btn_4: class extends self.ISpriteInstance {},
	btn_5: class extends self.ISpriteInstance {},
	btn_6: class extends self.ISpriteInstance {},
	btn_7: class extends self.ISpriteInstance {},
	btn_8: class extends self.ISpriteInstance {},
	btn_9: class extends self.ISpriteInstance {},
	Digit_10: class extends self.ITextInstance {},
	Digit_1: class extends self.ITextInstance {},
	Digit_11: class extends self.ITextInstance {},
	Digit_12: class extends self.ITextInstance {},
	Digit_13: class extends self.ITextInstance {},
	Digit_14: class extends self.ITextInstance {},
	Digit_15: class extends self.ITextInstance {},
	Digit_16: class extends self.ITextInstance {},
	Digit_2: class extends self.ITextInstance {},
	Digit_3: class extends self.ITextInstance {},
	Digit_4: class extends self.ITextInstance {},
	Digit_5: class extends self.ITextInstance {},
	Digit_6: class extends self.ITextInstance {},
	Digit_7: class extends self.ITextInstance {},
	Digit_8: class extends self.ITextInstance {},
	Digit_9: class extends self.ITextInstance {},
	Rating1: class extends self.ISpriteInstance {},
	Rating2: class extends self.ISpriteInstance {},
	Rating3: class extends self.ISpriteInstance {},
	Rating4: class extends self.ISpriteInstance {},
	Rating5: class extends self.ISpriteInstance {},
	Rating6: class extends self.ISpriteInstance {},
	Rating7: class extends self.ISpriteInstance {},
	Rating8: class extends self.ISpriteInstance {},
	Rating9: class extends self.ISpriteInstance {},
	Rating10: class extends self.ISpriteInstance {},
	Rating11: class extends self.ISpriteInstance {},
	Rating12: class extends self.ISpriteInstance {},
	Rating13: class extends self.ISpriteInstance {},
	Rating14: class extends self.ISpriteInstance {},
	Rating15: class extends self.ISpriteInstance {},
	Rating16: class extends self.ISpriteInstance {},
	level_selection_background: class extends self.ITiledBackgroundInstance {},
	back_btn2: class extends self.ISpriteInstance {},
	level_box: class extends self.ISpriteInstance {},
	level_text: class extends self.ITextInstance {},
	soil: class extends self.ISpriteInstance {},
	RotatingIcon: class extends self.ISpriteInstance {},
	ground2: class extends self.ISpriteInstance {},
	FlowerPot2: class extends self.ISpriteInstance {},
	collectible: class extends self.ISpriteInstance {},
	level1_background: class extends self.ITiledBackgroundInstance {},
	Drag_Drop_Text: class extends self.ITextInstance {},
	Heart: class extends self.ISpriteInstance {},
	HeartCount: class extends self.ITextInstance {},
	soil2: class extends self.ISpriteInstance {},
	soil3: class extends self.ISpriteInstance {},
	Lose_text: class extends self.ISpriteInstance {},
	pauseFrame: class extends self.ISpriteInstance {},
	Pause_Text: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Text_Resume: class extends self.ITextInstance {},
	Text_Restart: class extends self.ITextInstance {},
	Text_Exit: class extends self.ITextInstance {},
	pause_btn: class extends self.ISpriteInstance {},
	LevelComplete: class extends self.ISpriteInstance {},
	WinFrame: class extends self.ISpriteInstance {},
	home_btn: class extends self.ISpriteInstance {},
	Next_btn: class extends self.ISpriteInstance {},
	Rating: class extends self.ISpriteInstance {},
	Retry_btn: class extends self.ISpriteInstance {},
	Ground: class extends self.ISpriteInstance {},
	Ball: class extends self.ISpriteInstance {},
	Anchor: class extends self.ISpriteInstance {},
	Target: class extends self.ISpriteInstance {},
	TargetZone: class extends self.ISpriteInstance {},
	RopeLine: class extends self.ISpriteInstance {},
	Dot: class extends self.ISpriteInstance {},
	DropWater: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	RedBallHorizontal: class extends self.ISpriteInstance {},
	RedBallVertical: class extends self.ISpriteInstance {},
	RedBallCircular: class extends self.ISpriteInstance {},
	Plank: class extends self.ISpriteInstance {},
	btnMovePlank: class extends self.ISpriteInstance {},
	Box: class extends self.ISpriteInstance {},
	btnMoveBox: class extends self.ISpriteInstance {},
	Teleporter: class extends self.ISpriteInstance {},
	FlowerPot: class extends self.ISpriteInstance {},
	Background: class extends self.ISpriteInstance {},
	Background2: class extends self.ISpriteInstance {},
	Background3: class extends self.ISpriteInstance {},
	Backgroun4: class extends self.ISpriteInstance {},
	Platform: class extends self.ISpriteInstance {},
	DropZone: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	pot_trigger: class extends self.ISpriteInstance {},
	btnMoveBox2: class extends self.ISpriteInstance {},
	btnMoveBox3: class extends self.ISpriteInstance {},
	Box2: class extends self.ISpriteInstance {},
	Box3: class extends self.ISpriteInstance {},
	Retrylogo: class extends self.ISpriteInstance {},
	Plank2: class extends self.ISpriteInstance {},
	btnMovePlank2: class extends self.ISpriteInstance {},
	seed: class extends self.ISpriteInstance {},
	Plank3: class extends self.ISpriteInstance {},
	btnMovePlank3: class extends self.ISpriteInstance {},
	RedBallIdeal: class extends self.ISpriteInstance {},
	CollisionPlank: class extends self.ISpriteInstance {},
	Water: class extends self.ISpriteInstance {},
	Box4: class extends self.ISpriteInstance {},
	btnMoveBox4: class extends self.ISpriteInstance {},
	Plank4: class extends self.ISpriteInstance {},
	btnMovePlank4: class extends self.ISpriteInstance {},
	Plank5: class extends self.ISpriteInstance {},
	btnMovePlank5: class extends self.ISpriteInstance {},
	BallTrailideal: class extends self.IParticlesInstance {},
	BallTrailHorizontal: class extends self.IParticlesInstance {},
	BallTrailVertical: class extends self.IParticlesInstance {},
	BallTrailcircular: class extends self.IParticlesInstance {},
	Rotating: class extends self.IParticlesInstance {},
	Level6_Background: class extends self.ITiledBackgroundInstance {},
	Box5: class extends self.ISpriteInstance {},
	btnMoveBox5: class extends self.ISpriteInstance {},
	level12_backgound: class extends self.ITiledBackgroundInstance {},
	Box6: class extends self.ISpriteInstance {},
	btnMoveBox6: class extends self.ISpriteInstance {},
	Plank6: class extends self.ISpriteInstance {},
	btnMovePlank6: class extends self.ISpriteInstance {},
	splash_background: class extends self.ITiledBackgroundInstance {},
	SplashBackground: class extends self.ISpriteInstance {},
	ProgressBar: class extends self.IProgressBarInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Family1: class extends self.ISpriteInstance {}
}